// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Nicola Iacovelli",
            "email": "nicolaiacovelli98@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get all the meals which satisfies the query parameters (startRange, endRange) or all meals if no query parameters are provided",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meal"
                ],
                "summary": "Get all meals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date of the range",
                        "name": "startRange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date of the range",
                        "name": "endRange",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-array_dto_MealDto"
                        }
                    }
                }
            },
            "post": {
                "description": "create a new meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meal"
                ],
                "summary": "Create meal",
                "parameters": [
                    {
                        "description": "Meal to create",
                        "name": "mealDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MealDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-dto_MealDto"
                        }
                    }
                }
            }
        },
        "/statistics/": {
            "get": {
                "description": "get the meal statistics for the provided date range (default is the past week)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meal"
                ],
                "summary": "Get meal statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date of the range",
                        "name": "startRange",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date of the range",
                        "name": "endRange",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-dto_MealStatisticsDto"
                        }
                    }
                }
            }
        },
        "/{mealId}/": {
            "get": {
                "description": "get the meal with the provided id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meal"
                ],
                "summary": "Get meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-dto_MealDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete the meal with the provided id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meal"
                ],
                "summary": "Delete meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-bool"
                        }
                    }
                }
            },
            "patch": {
                "description": "update the meal with the provided id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meal"
                ],
                "summary": "Update meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Meal to create",
                        "name": "mealDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.MealDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-dto_MealDto"
                        }
                    }
                }
            }
        },
        "/{mealId}/consumption/": {
            "get": {
                "description": "find all the consumption for the meal by mealId",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "food-consumption"
                ],
                "summary": "Get all consumption for the meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-array_dto_FoodConsumptionDto"
                        }
                    }
                }
            },
            "post": {
                "description": "add consumption for the meal by mealId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "food-consumption"
                ],
                "summary": "Add consumption for the meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Food Consumption",
                        "name": "foodConsumptionDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FoodConsumptionDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-dto_FoodConsumptionDto"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete consumption for the meal by mealId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "food-consumption"
                ],
                "summary": "Delete consumption for the meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Food consumption ID",
                        "name": "foodConsumptionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-bool"
                        }
                    }
                }
            },
            "patch": {
                "description": "update consumption for the meal by mealId",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "food-consumption"
                ],
                "summary": "Update consumption for the meal",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Meal ID",
                        "name": "mealId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Food Consumption",
                        "name": "foodConsumptionDto",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.FoodConsumptionDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.BaseResponse-dto_FoodConsumptionDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AvgKcalPerMealTypeDto": {
            "type": "object",
            "properties": {
                "avgKcal": {
                    "type": "number"
                },
                "mealType": {
                    "type": "string"
                }
            }
        },
        "dto.BaseResponse-array_dto_FoodConsumptionDto": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.FoodConsumptionDto"
                    }
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "dto.BaseResponse-array_dto_MealDto": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.MealDto"
                    }
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "dto.BaseResponse-bool": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "boolean"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "dto.BaseResponse-dto_FoodConsumptionDto": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/dto.FoodConsumptionDto"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "dto.BaseResponse-dto_MealDto": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/dto.MealDto"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "dto.BaseResponse-dto_MealStatisticsDto": {
            "type": "object",
            "properties": {
                "body": {
                    "$ref": "#/definitions/dto.MealStatisticsDto"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "dto.FoodConsumptionDto": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "foodId": {
                    "type": "string"
                },
                "foodName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kcal": {
                    "type": "number"
                },
                "mealId": {
                    "type": "string"
                },
                "quantityUsed": {
                    "type": "number"
                },
                "quantityUsedStd": {
                    "type": "number"
                },
                "transactionId": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "dto.MealDto": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kcal": {
                    "type": "number"
                },
                "mealType": {
                    "$ref": "#/definitions/model.MealType"
                },
                "name": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "dto.MealStatisticsDto": {
            "type": "object",
            "properties": {
                "averageWeekCalories": {
                    "type": "number"
                },
                "averageWeekCaloriesPerMealType": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AvgKcalPerMealTypeDto"
                    }
                },
                "averageWeekFoodCost": {
                    "type": "number"
                },
                "mostConsumedFood": {
                    "$ref": "#/definitions/dto.MostConsumedFoodDto"
                },
                "sumWeekFoodCost": {
                    "type": "number"
                }
            }
        },
        "dto.MostConsumedFoodDto": {
            "type": "object",
            "properties": {
                "foodId": {
                    "type": "string"
                },
                "foodName": {
                    "type": "string"
                },
                "quantityUsed": {
                    "type": "number"
                },
                "quantityUsedStd": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "model.MealType": {
            "type": "string",
            "enum": [
                "breakfast",
                "lunch",
                "dinner",
                "others"
            ],
            "x-enum-varnames": [
                "Breakfast",
                "Lunch",
                "Dinner",
                "Others"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/meal",
	Schemes:          []string{},
	Title:            "Food track be API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
